name: Close Stale Pull Requests

on:
  schedule:
    - cron: "0 7 * * 1"
  workflow_dispatch:

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Close Stale Pull Requests
        uses: actions/stale@v9
        with:
          days-before-pr-stale: 60 # Days until PR marked stale
          days-before-pr-close: 7 # Days after stale until PR closed
          stale-pr-label: "Stale"
          stale-pr-message: "This pull request has been marked as Stale because it has been inactive for more than 60 days. Please update this pull request or it will be automatically closed in 7 days."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: -1 # Never mark issues stale
          days-before-issue-close: -1 # Never close stale issues
